name: action_detection_project
channels:
  - pytorch
  - nvidia
  - conda-forge
  # - xformers
  - defaults
dependencies:
  - python>=3.9
  - pytorch>=2.0.0
  - torchvision>=0.15.1
  - pytorch-cuda>=11.7
  - cudatoolkit>=11.7
  - jupyter
  - jupyterlab
  - omegaconf
  - torchmetrics>=0.10.3
  - fvcore
  - iopath
  - matplotlib
  # - xformers=0.0.22
  - numpy
  # - opencv
  - scikit-learn
  - pip
  - pip:
#    - git+https://github.com/facebookincubator/submitit
    - --extra-index-url https://pypi.nvidia.com
    - cuml-cu11
    - opencv-python
    - xformers==0.0.22
    # - nbmerge
    # - PyQt5

  # Uncomment the following if you need additional packages:
  # - git+https://github.com/facebookincubator/submitit
